# Configuración del exportador Prometheus para Zartux Miner

exporter:
  listen_address: "0.0.0.0:9101"  # Escucha en todas las interfaces de red
  endpoint: "/metrics"            # Ruta para exposición de métricas
  timeout_ms: 5000                # Tiempo máximo de respuesta en milisegundos
  scrape_interval: "15s"          # Intervalo recomendado para la recolección de métricas

metrics:
  nonces:
    enabled: true
    default_labels:
      project: "zartrux"
      version: "1.0"
    custom_labels:
      - "algorithm"
      - "source"
      - "worker_id"
    rejection_reasons:
      - "invalid_hash"     # Hash inválido
      - "stale"            # Bloque obsoleto
      - "duplicate"        # Nonce duplicado
      - "low_difficulty"   # Dificultad insuficiente
      - "timeout"          # Expiración de tiempo
      - "pool_error"       # Error en el pool
    counters:
      received: "zartrux_nonces_received_total"   # Nonces recibidos
      used: "zartrux_nonces_used_total"          # Nonces utilizados en soluciones válidas
      rejected: "zartrux_nonces_rejected_total"  # Nonces rechazados por cualquier razón

  performance:
    enabled: true
    buckets:
      validation_time: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0]  # Tiempo en segundos
      hashrate: [1000, 5000, 10000, 50000, 100000, 500000]        # Hashes por segundo
      network_latency: [10, 50, 100, 500, 1000]                   # Latencia en ms
    histograms:
      validation_time: "zartrux_validation_time_seconds"   # Tiempo promedio de validación de nonce
      hashrate: "zartrux_hashrate_distribution"           # Distribución de tasa de hash
      network_latency: "zartrux_network_latency_ms"       # Latencia en la comunicación con el pool

  hardware:
    enabled: true
    metrics:
      - name: "cpu_usage"
        type: "gauge"
        help: "Uso de CPU en porcentaje"
        enabled: true
      - name: "memory_usage"
        type: "gauge"
        help: "Uso de memoria en MB"
        enabled: true
      - name: "gpu_usage"
        type: "gauge"
        help: "Uso de GPU en porcentaje"
        enabled: true    # Ahora activo para equipos con minería GPU
      - name: "disk_usage"
        type: "gauge"
        help: "Uso de disco en porcentaje"
        enabled: true
      - name: "temperature"
        type: "gauge"
        help: "Temperatura promedio de hardware"
        enabled: true    # Nueva métrica añadida

  network:
    enabled: true
    metrics:
      - name: "active_connections"
        type: "gauge"
        help: "Número de conexiones activas a pools"
        enabled: true
      - name: "reconnects"
        type: "counter"
        help: "Número total de reconexiones realizadas"
        enabled: true
      - name: "failed_connections"
        type: "counter"
        help: "Número de intentos de conexión fallidos"
        enabled: true
      - name: "data_transferred"
        type: "counter"
        help: "Cantidad total de datos enviados/recibidos en MB"
        enabled: true    # Métrica nueva para monitoreo del tráfico de red
